// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wikgeevbmzwtktaertkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indpa2dlZXZibXp3dGt0YWVydGt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NzczMjAsImV4cCI6MjA1NjQ1MzMyMH0.xcgd_NnHL3faJr-xJWJMNm4wbsfay-_uzZtVyRUNNU8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);